services:
  - type: web
    name: classbook-backend
    env: node
    plan: free
    rootDir: .  # Or your subfolder name if needed
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: node dist/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: classbook-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production