# services:
#   - type: web
#     name: classbook-backend
#     env: node
#     plan: free
#     rootDir: .  # Or your subfolder name if needed
#     buildCommand: npm install && npm run build && npx prisma generate
#     startCommand: node dist/server.js
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: classbook-db
#           property: connectionString
#       - key: JWT_SECRET
#         generateValue: true
#       - key: JWT_REFRESH_SECRET
#         generateValue: true
#       - key: NODE_ENV
#         value: production

services:
  - type: web
    name: classbook-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: classbook-db
          property: connectionString
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-min-32-chars-change-this-in-production
      - key: JWT_REFRESH_SECRET
        value: your-super-secret-refresh-key-min-32-chars-change-this-too
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001